version: "3.3"
services:
  api:
    environment:
      - FilePersistenceServiceOptions__UploadsDirectory=/static/u
      - CORS__Origin
      - Okta__OktaDomain
      - ConnectionStrings__Default
    container_name: sher
    build: .
    ports:
      - "9090:80"
    depends_on:
      - db
    volumes:
      - static:/static
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  nginx:
    image: nginx
    volumes:
      - static:/usr/share/nginx/html
    ports:
      - "9091:80"

volumes:
  static: