version: "3.3"
services:
  api:
    environment:
      - FilePersistenceServiceOptions__UploadsDirectory=/static/u
      - JwtOptions__SecurityKey
      - JwtOptions__Audience
      - JwtOptions__Issuer
      - PasswordHashingOptions__Iterations=1
      - PasswordHashingOptions__DegreeOfParallelism=2
      - PasswordHashingOptions__MemorySize=131072
      - ConnectionStrings__Default
      - Admin__EmailAddress
      - Admin__Password
    container_name: sher
    build: .
    ports:
      - "9090:80"
    depends_on:
      - db
    volumes:
      - static:/static
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  nginx:
    image: nginx
    volumes:
      - static:/usr/share/nginx/html
    ports:
      - "9091:80"

volumes:
  static: