version: "3.3"
services:
  api:
    container_name: sher
    build:
      context: .
      dockerfile: src/Sher.Api/Dockerfile
    depends_on:
      - db
  db:
    container_name: postgres
    build: .docker/postgres