version: "3.3"
services:
  api:
    container_name: sher
    build:
      args:
        APP_ENTRYPOINT: api
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres