version: "3.3"
services:
  api:
    container_name: sher
    build:
      context: .
      dockerfile: src/Sher.Api/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres