version: "3.3"
services:
  api:
    environment:
      - Tus__DiskStorePath=/static/u
      - JwtOptions__SecurityKey
      - JwtOptions__Audience
      - JwtOptions__Issuer
      - PasswordHashingOptions__Iterations=1
      - PasswordHashingOptions__DegreeOfParallelism=2
      - PasswordHashingOptions__MemorySize=131072
      - ConnectionStrings__Default
      - Admin__EmailAddress
      - Admin__Password
    ports:
      - "9090:80"
    volumes:
      - static:/static
  db:
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  static: