name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and test
      run: DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml -f docker-compose.tests.yml up --build tests
