name: CD

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Add SSH Credentials
        uses: shimatoro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    
      - name: Deploy
        uses: JorgenVatle/docker-compose-deploy@v1.0
        env:
          CORS__Origin: ${{ secrets.CORS_ORIGIN }}
          Okta__OktaDomain: ${{ secrets.OKTA_DOMAIN }}
          ConnectionStrings__Default: 'Database=sher;Username=sher;Password=${{ secrets.DB_PASSWORD }};Server=postgres'
          POSTGRES_USER: sher
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          deploy_targets: ${{ secrets.DEPLOY_TARGETS }}
          compose_file: 'docker-compose.production.yml'
