name: CD

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.DEPLOY_TARGETS }}
    
      - name: Deploy
        uses: JorgenVatle/docker-compose-deploy@v1.0
        env:
          CORS__Origin: ${{ secrets.CORS_ORIGIN }}
          Okta__OktaDomain: ${{ secrets.OKTA_DOMAIN }}
          ConnectionStrings__Default: 'Database=sher;Username=sher;Password=${{ secrets.DB_PASSWORD }};Server=postgres'
          POSTGRES_USER: sher
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          deploy_targets: ${{ secrets.DEPLOY_TARGETS }}
          compose_file: 'docker-compose.production.yml'
