name: CD

on:
  workflow_dispatch:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.1.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.DEPLOY_TARGETS }}
    
      - name: Deploy
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          JwtOptions__SecurityKey: ${{ secrets.JWT_KEY }}
          JwtOptions__Audience: ${{ secrets.JWT_AUDIENCE }}
          JwtOptions__Issuer: ${{ secrets.JWT_ISSUER }}
          Admin__EmailAddress: ${{ secrets.ADMIN_EMAIL }}
          Admin__Password: ${{ secrets.ADMIN_PASSWORD }}
          ConnectionStrings__Default: 'Database=sher;Username=sher;Password=${{ secrets.DB_PASSWORD }};Server=postgres'
          POSTGRES_USER: sher
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d --build
